# Generated by Django 3.1.7 on 2021-04-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('UserID', models.TextField(max_length=30)),
                ('Password', models.TextField(max_length=30)),
                ('FriendList', models.TextField()),
                ('ProfilePicture', models.ImageField(upload_to='')),
            ],
        ),
    ]
